version: "3"
services:
  legacy:
    restart: always
    build:
      context: ./src/legacy
      dockerfile: ./Dockerfile
    network_mode: "service:nginx"
    environment:
      - FLAG=Flatt{DUMMY}
      - RACK_ENV=production
  api:
    restart: always
    build:
      context: ./src/api
      dockerfile: ./Dockerfile
    depends_on:
      - legacy
    network_mode: "service:nginx"
    environment:
      - LEGACY=localhost:4567
  nginx:
    restart: always
    image: nginx:1.25.3
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/nginx/public/index.html:/public/index.html:ro
    ports:
      - 30001:30001
